"""Add preview_image to templates

Revision ID: c5b6a70798e1
Revises: 6d37d5eb54be
Create Date: 2025-04-20 19:16:54.449176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b6a70798e1'
down_revision: Union[str, None] = '6d37d5eb54be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
     # 1) add as nullable
    op.add_column(
        'templates',
        sa.Column('preview_image', sa.String(), nullable=True),
    )
    # 2) back‑fill existing rows
    op.execute(
        "UPDATE templates "
        "SET preview_image = '/static/previews/modern.png' "
        "WHERE name = 'Modern';"
    )
    op.execute(
        "UPDATE templates "
        "SET preview_image = '/static/previews/classic.png' "
        "WHERE name = 'Classic';"
    )
    # 3) enforce NOT NULL
    op.alter_column('templates', 'preview_image', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('templates', 'preview_image')
    # ### end Alembic commands ###
